### ISSUE TITLE
Add support for others messages to be used as RL messages

### ISSUE THREAD

**Issue by Edwinexd** [eibex/reaction-light#56]
**Is your feature request related to a problem? Please describe.**

\- (See *Describe the solution you'd like*)

**Describe the solution you'd like**

I'd like to be able to use other users messages e.g. users or other bots messages as reaction messages instead of only being able to use the bots own messages as "role switchers". The use case for this is when you for example have multiple rule messages but only need reaction capability on one of them.

The solution I'm thinking is by adding an option in the RL creation process to use a existing message or create one using the bot. 

**Describe alternatives you've considered**

Creating reaction light messages that have no emoji/role combinations attached to them. I've decided against using this due to the unnecessary DB-entries. I've also considered to just add a entry to the database manually but thought others might have the same use case.

**Additional context**

I can help implement it, just want to see it is something that is seem fit inside the scope of the project.

**Comment by eibex** [comment]
Hey, this was actually on my pre-1.0.0 roadmap and I forgot about it when working on other core functionalities. 

This is definitely something that could be implemented, but I wonder if there's any way to implement this efficiently without using developer mode (I think we would need to feed the bot with the message id). Do you have any idea to do this without developer mode?

The only thing that comes to mind is something that lists messages like `rl!edit` when there are multiple reactionrole messages in the same channel. But that would feel extremely tedious.

Otherwise we could make an exception to the rule since this would be an extra feature that is already covered by a solution that doesn't rely on developer mode. 

Instead of making a new command I would probably modify the `on_message` event step that asks to insert the text for the reaction role message to also accept the option of a message id.

Let me know if you have any opinion on anything that I just wrote.

**Comment by eibex** [comment]
Another option would be to make the `rl!new` command accept an optional argument which would be the target message id. 

If this was selected the reactionrole message creation process would finish before asking the user to insert the text data for the embed and just add the reactions to the target message. 

The downside of this is that users would need to actually read the README or the `rl!help` information to know this functionality exists.

**Comment by Edwinexd** [comment]
Hey! I think editing the `on_message` is the best choice here and for selecting what message to use, we could use the message link that users can copy for any message they look something like this: https://discord.com/channels/<guild_id>/<channel_id>/<message_id> and then parse that via something like this:
`
link = inputlink.split('/')
guild_id = int(link[4])
channel_id = int(link[6])
message_id = int(link[5])
`
(would need some try/except to notify users of invalid links)

Btw, while running `rl!new` to inspect the creation process I realized that it asks for the channel at first, while not an issue might be better of coming just before writing the message as we then could have an alternative just before that to choose if we want to use an old message or create one using the bot. So the new creation process would be: roles -> Ask user if they want an old/new message -> if they want and old message we ask them for a link otherwise create one using the other system.
Alternatively which I think would be better is to do it in this order:
Ask user if they want an old/new message -> if they want and old message we ask them for a link otherwise create one using the other system -> emoji/role


While scrolling through the `on_message`  I realize that bot.wait_for is not used (see: https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.wait_for) although it works as it is it seems a bit overkill to do that many db read/writes during the message creation. I can re-work that with wait_for as it would make the code a lot more readable and easier to manage. (I have some code I can re-use from one of my bots)

As for editing `rl!new`, while it could work I'd say its better to do it the way I proposed above. 

Let me know what you think 👍 (btw add me on Discord so we can ease communication Edwin#3726)
