### ISSUE TITLE
Support embed thumbnails/pictures

### ISSUE THREAD

**Issue by Melons-le** [eibex/reaction-light#59]
Just a way to add thumbnail (with url image)

**Comment by eibex** [comment]
on top the URL image the bot should also accept user uploaded images (download the attachment and reupload it as another attachment)

**Comment by alexanderJHarris** [comment]
I'd like to take a crack at this, I understand you wish to deprecate discord.py in favor of Rust. I can write this up in python and later help implement it in Rust. I am also learning Rust at this time

**Comment by eibex** [comment]
It would be very appreciated. Though I must warn that the conversion to Rust is taking a long time due to my work schedule, if a new fork of discord.py that supports slash commands comes to be I will probably switch to that instead of Rust to avoid a complete rewrite.

**Comment by d7415** [comment]
> if a new fork of discord.py that supports slash commands comes to be and appears to be stable and well maintained I will probably switch to that instead of Rust to avoid a complete rewrite

I've been looking at https://github.com/DisnakeDev/disnake/ which has added [slash commands](https://disnake.readthedocs.io/en/latest/ext/commands/slash_commands.html).

**Comment by eibex** [comment]
Thanks for the heads up. I will keep monitoring that repository.

**Comment by alexanderJHarris** [comment]
Awesome I'll get started over the weekend, I'll also keep track of the disnake repo and brush up on it in case you guys choose to adopt this as well!

**Comment by eibex** [comment]
@alexanderJHarris I'm not sure if you made any progress on the PR, but if you want to bake it into the edit command, I would suggest you to take a look at #87 and use the slash-command-ready function there. I started with that function with this in mind since moving to slash commands is mandatory by April 2022.

However, I'm not sure if you can attach images to slash commands, a work around would be passing the URL instead of an image.

**Comment by alexanderJHarris** [comment]
@eibex Haven't had a good amount of time to go through this with work and the holiday coming up. I'll do my best to make more headway this upcoming week.

**Comment by eibex** [comment]
No worries, just wanted to give you some head ups in case you still wanted to work on it.
It would be a shame if you worked on a feature that needs to be reworked due to the new Discord API.

You can also look at the disnake PR (#88) if you prefer it over edpy (porting the change between the two should be relatively easy).

Of course, do not worry if you do not have time to do it soon, the new API comes into effect in 2022, plenty of time :)
