### ISSUE TITLE
Something went wrong :|

### ISSUE THREAD

**Issue by PRINCE-HERE** [eibex/reaction-light#84]
![Screenshot_2021_0917_181344](https://user-images.githubusercontent.com/86729260/133790194-cfe190c7-bd40-407e-bd04-fd437b9e5998.png)
![Screenshot_2021_0917_181324](https://user-images.githubusercontent.com/86729260/133790206-5e2f08a4-1aec-4e56-9f17-056beda034b7.png)
 
this happened when I typed "pip install dotenv" in shell (I use replit) I'm using my phone (Vivo 1604)
Please help me if you know whats wrong :)

**Comment by Edwinexd** [comment]
Hi there! This issue seems to have nothing to do with Reaction Light as it does not utilize `dotenv` for configuration, it instead relies on a config.ini file (which you can create using `setup.py`.

On another note, you will not be able to host Reaction light as it is on replit since it relies on a database file & configuration file which will end up getting deleted every time the project re-launches (if I recall correctly) practically rendering the bot useless.

The recommended way to host RL is using a Linux-based VPS from a provider like Digitalocean/Vultr (instructions on this is available in the [readme](https://github.com/eibex/reaction-light#setup)).
