### ISSUE TITLE
Bot doesnt start anymore after update

### ISSUE THREAD

**Issue by Mega-Bits** [eibex/reaction-light#96]
**Describe the bug**

Bot doesnt start after update

**To Reproduce**

`python3 bot.py`

**Expected behavior**

Bot Starts.

**Screenshots**

**Server:**

- OS: Debian 10
- Python version: Python 3.8.10
- discord.py version: ???

**Traceback**

```
Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    import disnake
ModuleNotFoundError: No module named 'disnake'
```

**Comment by Edwinexd** [comment]
Hey! As mentioned in the [latest patch notes](https://github.com/eibex/reaction-light/blob/master/CHANGELOG.md#300) you need to take some additional steps after updating from 2.x.x to 3.0.0:
  - BEFORE updating you need to replace discord.py since it's [no longer developed](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1) and update your bot permissions:
    - Make sure your Python version is 3.8 or greater
    - `python3 -m pip uninstall discord.py`
    - `python3 -m pip install -U disnake` (or `python3 -m pip install -r requirements.txt` while in the bot directory)
    - Reauthorize your bot with the following link: `https://discord.com/oauth2/authorize?&client_id=CLIENT_ID&scope=bot%20applications.commands&permissions=2415978560` (replace CLIENT_ID)
    - On https://discord.com/developers/applications select your bot and under the "Bot" setting turn on message content intent (no need for other intents)
    - Wait ~1 hour before Discord register your bot's commands (do not kick the bot to speed the process up without first shutting it down)

**Comment by Mega-Bits** [comment]
Sorry missed the notes.
